### PR TITLE
Fix bug where clearTimeout is set to setTimeout

### PR DESCRIPTION
**Pull request by Micro-Joe**

### CODE REVIEW

**Comment by Micro-Joe** [comment]
@tgorka @helgenlechner @Chalarangelo

Can you do a quick review to get this 1 line fix in?
Thanks!!

**Comment by tgorka** [comment]
Thanks for the contribution!

**Comment by Micro-Joe** [comment]
@tgorka 
Thanks!
Can you publish to npm with the fix?

**Comment by tgorka** [comment]
Yes I will do that in a week, when I will be back from the Christmas break and have access to the computer.

**Pull request merged**
